# Crown segmentation 

We are using supercells to create segmentated crowns using:
  - A shapefile (.shp) with a grid of tree locations derived by georeferencing the census data to the imagery. This will be referred to as the “grid”. 
  - Co-registered CHM made from normalized maximum  elevation (Z) values, MicaSense orthomosaic, and P1 orthomosaic, ideally from the same date 



1. Creates a 2D .shp file representing the location of each tree from a csv of census data including row and col data per tree. This .shp will be refered to as the grid 

2.  Usisng the CHM, finds treetops and snaps each tree in the grid to a treetop found within a 40cm radius 

3. Check the location of the treetops to the P1 orthomosaic and manual move treetops to align with trees in the P1 orthomosaic where necessary. 

4. Load in manually edited treetops, create circles proportional to tree height. 

5. Create a segmentation raster using the CHM and MicaSense and P1 orthomosaics 

6. Filter out segments that do not touch any of the circles proportional to tree height 

7. Merge remaining segments to create crown polygons 

8. Load into a GIS, along with the edited treetops and P1 orthhtomosaic, and edit the crown polygons to remove sections where neighbouring branches intersect the crown to ensure the crowns contain only data from the correct tree 