# Background and basis of knowledge

In Canada and other countries with managed forest industries, operational forestry includes reforestation of harvested or naturally deforested land. In many widespread forest tree species, populations are locally adapted to their climates of origin, meaning that jurisdictions must determine which seed sources can be used in which environments to ensure the health and productivity of planted forests. These decisions are made using common-garden trials, experiments which test different genotypes in a common environment to isolate the genetic component of their physical traits, or phenotype.  For many decades, measurements of height and diameter have been used to identify desirable genotypes for a given environment, in other words, the trees that grow tallest in a climate represent the best seed sources to plant in that climate. 
However, the measurement of traits in common-garden trials, or phenotyping, represents a bottleneck in forest genetics because (1) it is time-consuming and expensive to phenotype thousands of large trees in remote field environments, and (2) simple traits of height and diameter may not capture signals of adaptation and resilience. Drone remote sensing technology has the potential to alleviate the forest genetics phenotyping bottleneck through (1) more efficient phenotyping of traditional target traits representing height and diameter growth, and (2) novel traits, such as spectral vegetation indices, representing foliar physiology and responses to stress.
 
In the western Canadian province of British Columbia (BC), where this research took place, remote sensing tools provide the opportunity for hundreds of forest genetics trials to be assessed for traditional traits like tree size and for novel climate-adaptive traits and tree health assessments. However, before these powerful tools can be adopted, their suitability in different environments must be assessed (i.e. sloped verse flat terrain, open canopy verse crown-closure, etc.).  
 
Over 2022 and 2023 we conducted more than 400 flights on six MOF forest genetics research trials collecting multispectral, LiDAR and thermal data. The six trials, located in two regions near Jordan River and Powell River in coastal BC, represent cool-moist and dry-warm coastal environments. Our repeated field campaigns over two years allowed us to capture several biologically relevant climatic windows, including heat and drought events, and to look at practical considerations on applying these tools by including two morphologically different conifer species at pre-selection and mature ages.  As the project continues into 2024, the methodology will be further refined on new sites and updated throughout this guide.

These guidelines were developed using drone-acquired data collected on forest genetics field trials known as progeny trials. Progeny trials involve crossing specific parent trees and testing offspring in replicated trials across a wide geographic area. Due to known parent-offspring relationships and family structures, it is possible to infer the heritability of a trait, or the proportion of phenotypic variance attributable to transmissible genetic variance. This information is key for forest geneticists since the gains from genetic selection rely on trait heritability and variability (selection intensity). Knowledge of relatedness also makes it possible to infer the value of parent trees and offspring for future crosses for the trait, known as breeding values. Evaluating the correlation of genetic variations among traits is another important component in tree breeding since positive genetic correlations may allow simultaneous selection for two desirable traits (indirect selection) while negative genetic correlations require special treatment to mitigate trade-offs. It is also critical to understand how tree genotypes’ responses vary across environments (genotype-by-environment interactions), since stability of trait expression affects tree breeding and seed deployment.
