# Data Processing: Software and hardware costs and options

**Software costs**
We chose open-source options where we could, but there are still significant software costs. Table \@ref(tab:software-cost) outlines cost and explores options.

```{r software-cost, echo = FALSE}
library(knitr)
library(kableExtra)
data <- data.frame(
  Software  = c("DJI Terra Pro",
                "Agisoft Metashape Pro",
                "LasTools",
                "RedToolBox"
                 
  ),
  Purpose = c("Raw LiDAR processing",
              "Photogrammetry processing",
              "LiDAR processing",
              "PPK and geotagging"
              
  ),
  Cost = c("$6,000 plus $500 yearly",
           "$4,700",
           "$3,100",
           "$300"
  ),
  Options_notes = c("None, DJI LiDAR can only be processed in DJI Terra, and the yearly updates have included significant improvements",
                    "Agisoft is industry standard.  Pix4D is often compared, but more for online processing.  Open Drone map (ODM) is a free open-source alternative, but has not been tested by this team.",
                    "Excellent software that runs quickly, but most of the functions we used can be written in R.",
                    "PPK can be free in RTKLiB. Recently, the free Emlid Studio V1.8 update can PPK and geotag."
  )
  
  
)
# Create the table and center it
kable(data, col.names = c("Software", "Purpose","Cost","Options - notes"),caption = "Purpose, cost, and notes on software that we have used for this project.")

```


**Data management: Storage needs** 

Each project will have very different storage needs, but this will be a rough guide to help plan for the quantity of storage required and can be scaled according to project goals. 


One flight per sensor: 

L1 - 2Ha site produces ~510 pictures and approximately 8.5 GB of raw data total. 

P1 - 2Ha flight area produces ~500 photos and 12 GB of data. 

MS_P - 2Ha flight area produces around 12,000 photos equaling 42 GB. 

H20T - 2Ha flight area produces aproximately 1500 RGB and thermal images equaling ~20GB.  

We are keeping all intermediate products while we are developing processes.  Processing more than doubles the raw data.  Consider 250GB a conservative estimate for total data storage needs for the one day on site.   

A copy of the folder structure we use is available on GitHub 

**Computer Hardware:** 

The computer we are using has the following specifications 

Processor	Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz   2.39 GHz  (2 processors) 

Installed RAM	256 GB  

System type	64-bit operating system, x64-based processor 

GPU		NVIDIA RTX A4000Raw Data Collection 

2TB SSD for processing, we have found the processing is consistently faster and less prone to error if we process on the SSD rather than on the storage drives. 


For storage we use an 8bay QNAP RAID6 with 12 TB hard drives.  

We use 18Tb HDs for backups. 